### ISSUE TITLE
APCs are fockeen broken

### ISSUE THREAD

**Issue by ClickerOfThings** [spacepunch13/fpstation#88] opened 2019-05-25 13:58 UTC
[Round ID]: 887 & 886 (and maybe some previous one idk)

So, APCs are broken from the last commits.
They randomly "turn off" at any time, even if it is charged, and need to be turned off and on manually to get machines work.
The thing is, APCs power channels are not "turning off". The main clause is zero draining (0 W thing), no matter if it is set on "Auto" or "On".
Example here: https://cdn.discordapp.com/attachments/409698100437843985/581842934442360876/unknown.png
Kinda gay bug.

**Comment by richpet9** [comment] 2019-05-28 17:48
This was resolved with the revert, and shouldn't be an issue with the new PR.

This was caused by a phantom zone, basically, the entire station was duplicated exactly on top of itself, resulting in APC not knowing where to route their power, to the real station or phantom station. 

Resolved by un-including the map .dmm from the .dme compile.

**Closed as completed** 2019-05-28 19:16 UTC
